// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Sep 29 15:53:50 2018

FULL_ADDER_SYMBOL FULL_ADDER_SYMBOL_inst
(
	.grygorczuk_carry_in(grygorczuk_carry_in_sig) ,	// input  grygorczuk_carry_in_sig
	.grygorczuk_input_1(grygorczuk_input_1_sig) ,	// input  grygorczuk_input_1_sig
	.grygorczuk_input_2(grygorczuk_input_2_sig) ,	// input  grygorczuk_input_2_sig
	.grygorczuk_output(grygorczuk_output_sig) ,	// output  grygorczuk_output_sig
	.grygorczuk_carry_out(grygorczuk_carry_out_sig) 	// output  grygorczuk_carry_out_sig
);

